obstacle_range: 4.0
raytrace_range: 3.0

footprint: [[-0.1, -0.2], [0.1, -0.2], [0.1, 0.2], [-0.1, 0.2]]
# robot_radius: 0.2
inflation_radius: 0.2

observation_sources: laser_scan
laser_scan: {sensor_frame: lidar_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
 
