frequency: 30  # Частота фильтрации

# Входы от одометрии
odom0: /diff_drive_robot/odom
odom0_config: [true, true, false, false, false, true]
odom0_differential: false
odom0_queue_size: 10

# Входы от SLAM
pose0: /slam_out_pose
pose0_config: [true, true, false, false, false, true]
pose0_differential: false
pose0_queue_size: 10

# Параметры публикации
world_frame: map
odom_frame: odom
base_link_frame: base_link
publish_tf: true
