global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 1.0
  static_map: false  # Тк используем SLAM а не готовую карту  
  rolling_window: true
  resolution: 0.05 

  transform_tolerance: 1
 
