local_costmap:
  global_frame: map # как в глобал костмап конфиге 
  robot_base_frame: base_link # как в глобал костмап конфиге 
  update_frequency: 5.0 # как в глобал костмап конфиге 
  publish_frequency: 4.0
  static_map: false # как в глобал костмап конфиге 
  rolling_window: true
  width: 2.5
  height: 2.5
  resolution: 0.02

  transform_tolerance: 1

  # plugins:
  #   - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  #   - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

  # inflation_layer:
  #   inflation_radius: 0.5
  #   cost_scaling_factor: 10.0
